# Generated by Django 5.2.16 on 2026-07-24 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0002_categoria_evento_coletivo_imagemevento_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontodeinteresse',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='pontodeinteresse',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='evento_data_fim_apos_inicio'),
        ),
    ]
