# Generated by Django 5.2.16 on 2026-07-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_alter_pontodeinteresse_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetivoSlugAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Único — um slug jamais aponta para dois coletivos.', max_length=220, unique=True, verbose_name='slug anterior')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('coletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs_anteriores', to='rede.coletivo', verbose_name='coletivo')),
            ],
            options={
                'verbose_name': 'slug anterior de coletivo',
                'verbose_name_plural': 'slugs anteriores de coletivos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
